name: Lab-3 CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: create ssh key
        run: ${{ secrets.SSH_KEY }} > touch ~/.ssh/id_ed25519.pub
      - name: shh onto the VM
        run: sudo ssh admin@51.250.121.169
      - name: pull the latest image
        run: sudo docker pull cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/lab-3:theflaskimage
      - name: run latest image
        run: sudo docker run -p 3000:3000 cr.yandex/${{ secrets.YANDEX_CONTAINER_REGISTRY_ID }}/lab-3:theflaskimage